# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('track_id', models.CharField(default='', max_length=150)),
                ('album_art_url', models.CharField(default='', max_length=200)),
                ('artist_name', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
