# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyID', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('album_type', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyID', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SongMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyID', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('preview_url', models.URLField()),
                ('track_number', models.IntegerField()),
                ('disc_number', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.AlbumMetadata')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.ArtistMetadata')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.SongMetadata'),
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist'),
        ),
    ]
