# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='metadata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playlist.PlaylistMetadata'),
            preserve_default=False,
        ),
    ]
